# Generated by Django 5.0.4 on 2024-05-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contextAR', '0002_wordindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordIndex',
        ),
    ]
